curl http://0.0.0.0:4000/api/anagrams/check -H "Content-Type:application/json" --data '{"firstword":"ballbase", "secondword":"baseball"}' --silent --output /dev/null --show-error
curl http://0.0.0.0:4000/api/anagrams/check -H "Content-Type:application/json" --data '{"firstword":"ballbase", "secondword":"baseball"}' --silent --output /dev/null --show-error
curl http://0.0.0.0:4000/api/anagrams/check -H "Content-Type:application/json" --data '{"firstword":"ballbase", "secondword":"baseball"}' --silent --output /dev/null --show-error
curl http://0.0.0.0:4000/api/anagrams/check -H "Content-Type:application/json" --data '{"firstword":"wolf", "secondword":"fold"}' --silent --output /dev/null --show-error
curl http://0.0.0.0:4000/api/anagrams/check -H "Content-Type:application/json" --data '{"firstword":"wolf", "secondword":"folw"}' --silent --output /dev/null --show-error
curl http://0.0.0.0:4000/api/anagrams/check -H "Content-Type:application/json" --data '{"firstword":"wolf", "secondword":"folw"}' --silent --output /dev/null --show-error
curl http://0.0.0.0:4000/api/anagrams/check -H "Content-Type:application/json" --data '{"firstword":"wolf", "secondword":"fol"}' --silent --output /dev/null --show-error
curl http://0.0.0.0:4000/api/anagrams/check -H "Content-Type:application/json" --data '{"firstword":"olf", "secondword":"fol"}' --silent --output /dev/null --show-error
curl http://0.0.0.0:4000/api/anagrams/check -H "Content-Type:application/json" --data '{"firstword":"olf", "secondword":"fol"}' --silent --output /dev/null --show-error
curl http://0.0.0.0:4000/api/anagrams/check -H "Content-Type:application/json" --data '{"firstword":"wolf", "secondword":"fol"}' --silent --output /dev/null --show-error
curl http://0.0.0.0:4000/api/anagrams/check -H "Content-Type:application/json" --data '{"firstword":"wolf", "secondword":"folw"}' --silent --output /dev/null --show-error
curl http://0.0.0.0:4000/api/anagrams/check -H "Content-Type:application/json" --data '{"firstword":"wolf", "secondword":"folw"}' --silent --output /dev/null --show-error
curl http://0.0.0.0:4000/api/anagrams/check -H "Content-Type:application/json" --data '{"firstword":"restful", "secondword":"fluster"}' --silent --output /dev/null --show-error
curl http://0.0.0.0:4000/api/anagrams/check -H "Content-Type:application/json" --data '{"firstword":"keen", "secondword":"knee"}' --silent --output /dev/null --show-error
curl http://0.0.0.0:4000/api/anagrams/check -H "Content-Type:application/json" --data '{"firstword":"oww", "secondword":"wow"}' --silent --output /dev/null --show-error
curl http://0.0.0.0:4000/api/anagrams/check -H "Content-Type:application/json" --data '{"firstword":"oww", "secondword":"wwo"}' --silent --output /dev/null --show-error
curl http://0.0.0.0:4000/api/anagrams/check -H "Content-Type:application/json" --data '{"firstword":"yorc", "secondword":"cory"}' --silent --output /dev/null --show-error
curl http://0.0.0.0:4000/api/anagrams/check -H "Content-Type:application/json" --data '{"firstword":"yroc", "secondword":"cory"}' --silent --output /dev/null --show-error
curl http://0.0.0.0:4000/api/anagrams/check -H "Content-Type:application/json" --data '{"firstword":"yroc", "secondword":"ocry"}' --silent --output /dev/null --show-error
curl http://0.0.0.0:4000/api/anagrams/check -H "Content-Type:application/json" --data '{"firstword":"ryoc", "secondword":"ocry"}' --silent --output /dev/null --show-error
curl http://0.0.0.0:4000/api/anagrams/check -H "Content-Type:application/json" --data '{"firstword":"ballbase", "secondword":"baseball"}' --silent --output /dev/null --show-error
curl http://0.0.0.0:4000/api/anagrams/check -H "Content-Type:application/json" --data '{"firstword":"ballbase", "secondword":"esbaball"}' --silent --output /dev/null --show-error
curl http://0.0.0.0:4000/api/anagrams/check -H "Content-Type:application/json" --data '{"firstword":"bllabase", "secondword":"esbaball"}' --silent --output /dev/null --show-error
curl http://0.0.0.0:4000/api/anagrams/check -H "Content-Type:application/json" --data '{"firstword":"bllabase", "secondword":"esbaball"}' --silent --output /dev/null --show-error
curl http://0.0.0.0:4000/api/anagrams/check -H "Content-Type:application/json" --data '{"firstword":"ryoc", "secondword":"ocry"}' --silent --output /dev/null --show-error
curl http://0.0.0.0:4000/api/anagrams/check -H "Content-Type:application/json" --data '{"firstword":"ryoc", "secondword":"ocry"}' --silent --output /dev/null --show-error
curl http://0.0.0.0:4000/api/anagrams/check -H "Content-Type:application/json" --data '{"firstword":"bllabase", "secondword":"esbaball"}' --silent --output /dev/null --show-error
curl http://0.0.0.0:4000/api/anagrams/check -H "Content-Type:application/json" --data '{"firstword":"ballbase", "secondword":"esbaball"}' --silent --output /dev/null --show-error
curl http://0.0.0.0:4000/api/anagrams/check -H "Content-Type:application/json" --data '{"firstword":"yroc", "secondword":"ocry"}' --silent --output /dev/null --show-error
curl http://0.0.0.0:4000/api/anagrams/check -H "Content-Type:application/json" --data '{"firstword":"bllabase", "secondword":"esbaball"}' --silent --output /dev/null --show-error
curl http://0.0.0.0:4000/api/anagrams/check -H "Content-Type:application/json" --data '{"firstword":"ballbase", "secondword":"baseball"}' --silent --output /dev/null --show-error
curl http://0.0.0.0:4000/api/anagrams/check -H "Content-Type:application/json" --data '{"firstword":"ballbase", "secondword":"baseball"}' --silent --output /dev/null --show-error
curl http://0.0.0.0:4000/api/anagrams/check -H "Content-Type:application/json" --data '{"firstword":"ballbase", "secondword":"baseball"}' --silent --output /dev/null --show-error